name: Build Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend/
          echo "Package.json contents:"
          cat frontend/package.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          echo "Installing dependencies in $(pwd)"
          npm install
          echo "Dependencies installed successfully"
          echo "Node modules installed:"
          ls -la node_modules/ | head -10
      
      - name: Build
        working-directory: ./frontend
        run: |
          echo "Building frontend in $(pwd)"
          npm run build
          echo "Build completed successfully"
          echo "Build directory contents:"
          ls -la build/
          echo "Build static files:"
          ls -la build/static/
      
      - name: Build success
        run: |
          echo "🎉 Frontend build completed successfully!"
          echo "The build process works correctly."
          echo "Next step: Enable GitHub Pages in repository settings"
